### ISSUE TITLE
No drives shown on Free Play

### ISSUE THREAD

**Issue by harre096** [dstelljes/umm-floppy-choir#16]
This issue has been happening off and on and the cause needs investigation. My first question is if the right number is being pulled into the server. I added a printout (first hit when I play a song) and it says

Nov 21 00:44:37 sloppy floppy-control-app[19481]: NaN floppy drives have been attached.

Huh.

**Comment by dstelljes** [comment]
What line is your console.log on?

**Comment by harre096** [comment]
server.js:
io.on('connection', function(socket) {
  socket.on('get drive count', function() {
    var driveCount = controller.getDriveCount();
    console.info('%d floppy drives have been attached.', driveCount);
    socket.emit('drive count', driveCount);
  });

**Comment by dstelljes** [comment]
Maybe try lib/floppyController.js, lines 155ff. If that's firing often, the problem is probably in the Arduino code.

**Comment by dstelljes** [comment]
Also likely fixed with the interface refactor, maybe c74d8d3? Haven't been able to reproduce the issue since, but reopen if necessary.
