### ISSUE TITLE
It doesn't taste like Christmas

### ISSUE THREAD

**Issue by kylehakala** [dstelljes/umm-floppy-choir#19]
There should be some more fa la la la las or jingles or sleigh bells. Here are links to midi files that have them and a zip with all the files renamed. 
[songs.zip](https://github.com/dstelljes/umm-floppy-choir/files/598037/songs.zip)

https://www.westnet.com/Holiday/midi/deckthe.mid
https://www.westnet.com/Holiday/midi/to_town.mid
https://www.westnet.com/Holiday/midi/wondrlan.mid
https://www.westnet.com/Holiday/midi/gs_jbl2.mid

**Comment by dstelljes** [comment]
Added with e31fed7. If, after deployment, it still doesn't taste like Christmas, consult a doctor.

**Comment by dstelljes** [comment]
Aaaand it's live.
